-- Generated by Oracle SQL Developer REST Data Services 21.4.2.018.1706
-- Exported REST Definitions from ORDS Schema Version 21.4.3.r1300919
-- Schema: SENSOR_DATALAKE1   Date: Tue May 31 15:46:22 CEST 2022
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SENSOR_DATALAKE1',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'sensor_datalake1',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'sens',
      p_base_path      => '/sens/',
      p_items_per_page =>  10000,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sens',
      p_pattern        => 'any_sensor_data_entry/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sens',
      p_pattern        => 'any_sensor_data_entry/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM any_sensor_data_entry'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sens',
      p_pattern        => 'any_sensor_data_entry/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN 

                          create_one_sensor_data( 

p_sensor_id => :sensor_id, 

p_sensor_name => :sensor_name, 

p_sensor_type => :sensor_type, 

p_value1 => :value1, 

p_scale1 => :scale1, 

p_unit1 => :unit1, 

p_entry_document => :entry_document 

); 

                         END;'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'sens',
      p_pattern        => 'insert/',
      p_priority       => 9,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sens',
      p_pattern        => 'insert/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  10000,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM sensor_data'
      );
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'sens',
      p_pattern        => 'insert/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_items_per_page =>  0,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN 

insert_sensor_data(

p_sensor_id => :sensor_id,  

p_value1 => :value1,

p_unit1 => :unit1

);

END;'
      );


  COMMIT; 
END;